### ISSUE TITLE
Addon not starting

### ISSUE THREAD

**Issue by alanmilinovic** [OPHoperHPO/hassio-addons#8]
I cannot start addon, tired in Portainer as well and no luck.

This is the error I am getting:
`s6-overlay-suexec: fatal: can only run as pid 1`

**Comment by MattWestb** [comment]
I think this is some changed is made in HA that is making it not working.
https://developers.home-assistant.io/blog/2022/05/12/s6-overlay-base-images/
Also more info https://github.com/just-containers/s6-overlay/blob/master/MOVING-TO-V3.md.

I have one armbian ubuntu 22.04 running on one RK3218 box and i can install docker and HA with patching the installing (so grub is not needed) and its works OK if doing some manual things in docker.
In "hassio_audio" container -> edit -> Runtime & Resources and setting CPU 0.25 and the memory to 64 and "update limits" and its only using 25% CPU and not 200%.
The back side its needed being done after system is restarted also if only the addon is restarted as HA is deleting the setting and is using 200% CPU.

**Comment by MattWestb** [comment]
One well working work around found from one bug in HA 2022.6.
Edit the container and deleting the `/init` that is the default for the `ENTRYPOINT` record and then kicking `Override` and saving the container and starting it and its fixing the high CUP and then its suspending its self.
```
[ALSA&PULSEAUDIO FIX][INFO] Module `module-suspend-on-idle` loaded successfully!
```

**Comment by jmtatsch** [comment]
Same issue here

**Comment by timsavory** [comment]
> One well working work around found from one bug in HA 2022.6. Edit the container and deleting the `/init` that is the default for the `ENTRYPOINT` record and then kicking `Override` and saving the container and starting it and its fixing the high CUP and then its suspending its self.
> 
> ```
> [ALSA&PULSEAUDIO FIX][INFO] Module `module-suspend-on-idle` loaded successfully!
> ```

When I follow your fix by deleting the /init from entrypoint, select override and the deploy container it restarts in some way it was before.  Can you help explain what I am doing wrong?  Thanks Tim

**Comment by MattWestb** [comment]
My changed container config;
![HAAudiofix-docker](https://user-images.githubusercontent.com/49618193/173882381-f13962f5-f43b-4cf4-bff9-dd98603a4488.PNG)
only the endpoint and saving the changes and starting the addon from portainer or HA and its not throwing errors and fixing the 200% CPU usage and is backing out then have doing its work..

**Comment by timsavory** [comment]
> My changed container config; ![HAAudiofix-docker](https://user-images.githubusercontent.com/49618193/173882381-f13962f5-f43b-4cf4-bff9-dd98603a4488.PNG) only the endpoint and saving the changes and starting the addon from portainer or HA and its not throwing errors and fixing the 200% CPU usage and is backing out then have doing its work..

Thanks, I will give it a go....

**Comment by ntguest** [comment]
hi
i'm forked and repaired it 
u can try from this repo https://github.com/ntguest/hassio-audio

**Comment by OPHoperHPO** [comment]
Hi,

I've added an empty entry point for the docker container by default, as per @MattWestb's info and @ntguest fork changes. 
I don't have an instance of Home Assistant to test the addon at the moment, so i hope it will works.

**Comment by MattWestb** [comment]
I have updating HA to 2022.07 and was deleting the old addon and installing the updated version and restarting my NanpPI Neo and the addon is loaded OK and the not working sound is not eating 300% CPU so its looks working OK.

Thanks for fixing the issue HA have doing @OPHoperHPO  !!!
