### ISSUE TITLE
Failed to run add-on

### ISSUE THREAD

**Issue by timsavory** [OPHoperHPO/hassio-addons#9]
Hi,
I have just installed and tried to run but get the error:

 error is s6-overlay-suexec: fatal: can only run as pid 1

Appreciate your help please.

Thanks
Tim

**Comment by ntguest** [comment]
hi
i'm forked and repaired it 
u can try from this repo https://github.com/ntguest/hassio-audio

**Comment by OPHoperHPO** [comment]
Fixed. Check #8 for more info.

**Comment by MattWestb** [comment]
I have updating HA to 2022.07 and was deleting the old addon and installing the updated version and restarting my NanpPI Neo and the addon is loaded OK and the not working sound is not eating 300% CPU so its looks working OK.

Thanks for fixing the issue HA have doing @OPHoperHPO  !!!
